name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

{% if package_manager == 'Esy' -%}
{% raw -%}
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v2
      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install esy
        run: npm install -g esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install dependencies
        run: esy install

      - name: Build
        run: esy build --release

      - name: Check formatting
        run: esy format

      - name: Run tests
        run: esy test
        
      - name: Export dependencies
        run: esy export-dependencies
{%- endraw %}
{% else -%}
{% raw -%}
jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        ocaml-compiler:
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-depext-flags: --with-test

      - name: Install ocamlformat
        run: opam install ocamlformat.0.18.0
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install opam packages
        run: opam install . --with-test

      - name: Check formatting
        run: make fmt
        if: ${{ matrix.os == 'ubuntu-latest' && always() }}

      - name: Run build
        run: make build

      - name: Run the unit tests
        run: make test
        timeout-minutes: 1
{%- endraw %}
{% endif %}