name: CI

on: [push, pull_request]

{% if package_manager == 'Esy' -%}
{% raw -%}
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v2
      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install esy
        run: npm install -g esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install dependencies
        run: esy install

      - name: Build
        run: esy build --release

      - name: Check formatting
        run: esy format

      - name: Run tests
        run: esy test
        
      - name: Export dependencies
        run: esy export-dependencies
{%- endraw %}
{% else -%}
{% raw -%}
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-version: ['4.09.0', '4.08.1']
    steps:
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - uses: actions/checkout@v2

      - name: Pin package
        run: opam pin add {% endraw %}{{ project_slug }}{% raw %}.dev -n .

      - name: Query and install external dependencies
        run: opam depext -yt {% endraw %}{{ project_slug }}{% raw %}

      - name: Install dependencies
        run: make dev

      - name: Build
        run: make build

      - name: Check formatting
        run: make format

      - name: Run tests
        run: make test
{%- endraw %}
{% endif %}