name: CI

on: [push, pull_request]

{% raw -%}
jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        ocaml-compiler:
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}

      - name: Install ocamlformat
        run: opam install ocamlformat.0.18.0
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install opam packages
        run: opam install . --with-test

      - name: Check formatting
        run: make fmt
        if: ${{ matrix.os == 'ubuntu-latest' && always() }}

      - name: Run build
        run: make build

      - name: Run the unit tests
        run: make test
        timeout-minutes: 1
{% endraw -%}
